trigger:
  batch: true
  branches:
    include:
    - '*'

pr:
  paths:
    exclude:
     - "*.md"

jobs:

- job: 'Test'
  strategy:
    matrix:
      Python38Mac:
        imageName: "macos-latest"
        python.version: "3.8"
      Python38Windows:
        imageName: "windows-latest"
        python.version: "3.8"
      Python311Linux:
        imageName: "ubuntu-latest"
        python.version: "3.11"
    maxParallel: 4
  pool:
    vmImage: $(imageName)

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: python setup.py sdist
    displayName: 'Build sdist'

  - script: |
      pip freeze > installed.txt
      pip uninstall -y -r installed.txt
    displayName: "Uninstall all packages"

  - bash: pip install dist/*.tar.gz
    displayName: 'Install from sdist'

  - task: DeleteFiles@1
    inputs:
      contents: "spacy_experimental"
    displayName: "Delete source directory"

  - script: |
      pip install -r requirements.txt
      python -m pytest --pyargs spacy_experimental
    displayName: 'Run tests without PyTorch'

  - script: |
      pip install "torch==1.10.0+cpu" -f https://download.pytorch.org/whl/torch_stable.html
      python -m pytest --pyargs spacy_experimental
    displayName: 'Run tests with PyTorch'
